<?php

use PHPUnit\Framework\TestCase;
require_once('php_class/PriceCalculator.php');
require_once('./php_class/ClientProfileManagement.php');

    class PriceTest extends TestCase{

        //This function ensures that an HTML form is being generated by the function with database information.
        public function testPriceCalculator(): void
        {
            $this->assertTrue(PriceCalculator::suggestedPrice("cooldude9", 1) == "$1.71");
        }
        public function testOver1000(): void
        {
            $this->assertTrue(PriceCalculator::suggestedPrice("cooldude9", 1001) == "$1,696.70");
        }
        public function testOutofState(): void
        {
            $cpmTester = new ClientProfileManagement("cooldude9", "John Smith", "122 Green Rd", "244 Blue St", "Houston", "AL", "77201");
            $this->assertTrue(PriceCalculator::suggestedPrice("cooldude9", 1) == "$1.74");
        }
    }
