<?php

use PHPUnit\Framework\TestCase;
require_once('php_class/PriceCalculator.php');

    class PriceTest extends TestCase{

        //This function ensures that an HTML form is being generated by the function with database information.
        public function testPriceCalculator(): void
        {
            $this->assertTrue(PriceCalculator::suggestedPrice("cooldude9", 1) == "$1.71");
        }
        
    }
