<?php

use PHPUnit\Framework\TestCase;
require_once('php_class/PriceCalculator.php');
require_once('./php_class/ClientProfileManagement.php');

    class PriceTest extends TestCase{

        //This function ensures that an HTML form is being generated by the function with database information.
        public function testPriceCalculator(): void
        {
            $this->assertEquals("$1.71", PriceCalculator::suggestedPrice("cooldude9", 1));
        }

        public function testNewAccount(): void
        {
            $regTester = new ClientRegistration("cooldude19", "fluffy0000!");
            $cpmTester = new ClientProfileManagement("cooldude19", "John Smith", "122 Green Rd", "244 Blue St", "Houston", "TX", "77201");
            $this->assertEquals(PriceCalculator::suggestedPrice("cooldude19", 1), "$1.725");
        }

        public function testOver1000(): void
        {
            $this->assertEquals(PriceCalculator::suggestedPrice("cooldude9", 1001), "$1.695");
        }
        public function testOutofState(): void
        {
            $cpmTester = new ClientProfileManagement("cooldude9", "John Smith", "122 Green Rd", "244 Blue St", "Houston", "AL", "77201");
            $this->assertEquals(PriceCalculator::suggestedPrice("cooldude9", 1), "$1.74");
            $cpmTester = new ClientProfileManagement("cooldude9", "John Smith", "122 Green Rd", "244 Blue St", "Houston", "TX", "77201");

        }
    }
